service: myapp-ui
provider:
  name: aws
  stage: ${{opt:stage, self:custom.defaultStage}}
  profile: ${{self:custom.stages.${{self:provider.stage}}.profile}}
  region: us-east-1
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

plugins:
  - '@wizeline/serverless-amplify-plugin'

custom:
  defaultStage: dev
  stages:
    dev:
      profile: myapp_dev
      branch: dev
    staging:
      profile: myapp_staging
      domainName: staging.example.com
      branch: staging
    prod:
      profile: myapp_prod
      domainName: example.com
      branch: master
  amplify:
    repository: https://github.com/brettstack/myapp-play-by-cloud-turn-notifier
    branch: ${{self:custom.stages.${{self:provider.stage}}.branch}}
    domainName: ${{self:custom.stages.${{self:provider.stage}}.domainName, ''}}
    buildSpecValues:
      artifactBaseDirectory: packages/ui/build
      preBuildWorkingDirectory: packages/ui