service: myapp-db
provider:
  name: aws
  stage: ${{opt:stage, self:custom.defaultStage}}
  region: us-east-1
  profile: ${{self:custom.stages.${{self:provider.stage}}.profile}}
  runtime: nodejs8.10
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

plugins:
  - serverless-stack-output
  # - serverless-dynamodb-local

custom:
  defaultStage: dev
  stages:
    dev:
      profile: myapp_dev
    staging:
      profile: myapp_staging
    prod:
      profile: myapp_prod
  output:
    file: ./stack-outputs.yaml
  # dynamodb:
  #   stages:
  #     - dev
  #   start:
  #     port: 889
  #     migrate: true
  #     seed: true
  #   seed:
  #     User:
  #       sources:
  #         - table: User
  #           sources: [./db-seed/User.json]

resources:
  Resources:
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: User
          BillingMode: PAY_PER_REQUEST
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: false
          KeySchema:
            - KeyType: HASH
              AttributeName: id
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S

  Outputs:
    DynamoDbUserTableName:
      Description: DynamoDB Table User Table Name.
      Value: !Ref UserTable
    DynamoDbUserTableConsoleUrl:
      Description: Console URL for the DynamoDB Table.
      Value: !Sub 'https://console.aws.amazon.com/dynamodb/home?region=${AWS::Region}#tables:selected=${UserTable}'
