name: Test and release

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, ui]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    # - name: Install root
    #   run: npm ci
    
    - name: Install package
      working-directory: "./packages/${{ matrix.package }}"
      run: npm ci
    
    - name: Check for vulnerable dependencies in package
      working-directory: "./packages/${{ matrix.package }}"
      run: npm audit --audit-level high

    - name: Test
      working-directory: "./packages/${{ matrix.package }}"
      run: npm test

  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install root
      run: npm ci
    
    - name: Check for vulnerable dependencies in root
      run: npm audit --audit-level high
    
    - name: Deploy staging
      run: npm run deploy:staging -- --gitHubRunId=${{ github.run_id }}
    
    # TODO: Additional end-to-end tests

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [deploy-to-staging]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci && cd packages/ui && npm ci && cd ../api && npm ci
      
    - name: Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: npm run package
      
    - name: Release
      run: npx semantic-release
      env:
        # NOTE: GitHub Actions won't trigger on release when using the default GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
